//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OroPuro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Usuarios
    {
        [Required]
        [Index(IsUnique = true)]
        public int idUsr { get; set; }
        [Required(ErrorMessage = "Colocar Nombre")]
        [StringLength(20, ErrorMessage = "Email demasiado largo")]
        [RegularExpression("^[A-Za-z0-9 ]+$", ErrorMessage = "Nombre Incorrecto")]
        public string nomUsr { get; set; }
        [RegularExpression("^[A-Za-z0-9 ]+$", ErrorMessage = "Nombre Incorrecto")]
        public string apellPUsr { get; set; }
        [RegularExpression("^[A-Za-z0-9 ]+$", ErrorMessage = "Nombre Incorrecto")]
        public string apellMUsr { get; set; }
        public string telUsr { get; set; }
        [Required(ErrorMessage = "Colocar Email")]
        [StringLength(50, ErrorMessage ="Email demasiado largo")]
        [EmailAddress(ErrorMessage ="Formato Incorrecto")]
        public string emailUsr { get; set; }
        [Required(ErrorMessage = "Colocar Usuario")]
        [StringLength(20, ErrorMessage = "Email demasiado largo")]
        [RegularExpression("^[A-Za-z0-9 ]+$", ErrorMessage = "Usuario Incorrecto")]
        [Index(IsUnique = true)]
        public string usuarioUsr { get; set; }
        [Required(ErrorMessage = "Colocar Password")]
        [StringLength(20, ErrorMessage = "Email demasiado largo")]
        [RegularExpression("^[A-Za-z0-9 ]+$", ErrorMessage = "Password Incorrecto")]
        public string passUsr { get; set; }
        [Required(ErrorMessage = "Seleccionar Tipo")]
        [StringLength(20, ErrorMessage = "Email demasiado largo")]
        [RegularExpression("^[A-Za-z0-9 ]+$", ErrorMessage = "Tipo Incorrecto")]
        public string tipoUsr { get; set; }
        //public IEnumerable<SelectListItem> tipoUsr { get; set; }

    }
}
